# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Virtui < Formula
  desc "TUI automation for AI agents"
  homepage "https://github.com/honeybadge-labs/virtui"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/honeybadge-labs/virtui/releases/download/v0.1.1/virtui_darwin_amd64.tar.gz"
      sha256 "fe0d3a996f5a74a83fe6ce9320df302c0daa5eb26d8da5b272687f8a354faa1f"

      define_method(:install) do
        bin.install "virtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/honeybadge-labs/virtui/releases/download/v0.1.1/virtui_darwin_arm64.tar.gz"
      sha256 "d0346ace0973b90254cf6a0b545d023336321e8d471da692e2b6eda50dbd671d"

      define_method(:install) do
        bin.install "virtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/honeybadge-labs/virtui/releases/download/v0.1.1/virtui_linux_amd64.tar.gz"
      sha256 "846babcfab78b887b08a053a6be923b7eef759d72bb182f405358bb78585cb52"
      define_method(:install) do
        bin.install "virtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/honeybadge-labs/virtui/releases/download/v0.1.1/virtui_linux_arm64.tar.gz"
      sha256 "3e6220a2ff696158c025c68a01e5260199b85d19ae0fd5b92ad60f1ef76c62cb"
      define_method(:install) do
        bin.install "virtui"
      end
    end
  end
end
